const response = [
  {
    name: 'Grand Final: Virtus.pro vs fnatic',
    rescheduled: false,
    tournament: {
      begin_at: '2021-01-29T20:00:00Z',
      end_at: null,
      id: 5414,
      league_id: 4168,
      live_supported: true,
      modified_at: '2021-01-29T20:35:03Z',
      name: 'Playoffs',
      prizepool: null,
      serie_id: 3300,
      slug: 'cs-go-cs_summit-7-2021-playoffs',
      winner_id: null,
      winner_type: 'Team',
    },
    live_embed_url: 'https://player.twitch.tv/?channel=btscsgo',
    end_at: null,
    league_id: 4168,
    serie_id: 3300,
    serie: {
      begin_at: '2021-01-27T14:00:00Z',
      description: null,
      end_at: null,
      full_name: '7 2021',
      id: 3300,
      league_id: 4168,
      modified_at: '2021-01-21T18:43:07Z',
      name: '7',
      season: null,
      slug: 'cs-go-cs_summit-7-2021',
      tier: 'a',
      winner_id: null,
      winner_type: null,
      year: 2021,
    },
    modified_at: '2021-01-31T18:59:06Z',
    winner: null,
    videogame_version: null,
    original_scheduled_at: '2021-01-31T20:00:00Z',
    slug: 'virtus-pro-2021-01-31',
    videogame: {
      id: 3,
      name: 'CS:GO',
      slug: 'cs-go',
    },
    league: {
      id: 4168,
      image_url:
        'https://cdn.pandascore.co/images/league/image/4168/563px-Beyond_The_Summit_2018.png',
      modified_at: '2019-12-11T11:07:32Z',
      name: 'cs_summit',
      slug: 'cs-go-cs_summit',
      url: null,
    },
    results: [
      {
        score: 0,
        team_id: 3288,
      },
      {
        score: 0,
        team_id: 3217,
      },
    ],
    status: 'not_started',
    tournament_id: 5414,
    streams: {
      english: {
        embed_url: 'https://player.twitch.tv/?channel=btscsgo',
        raw_url: 'https://www.twitch.tv/btscsgo',
      },
      official: {
        embed_url: 'https://player.twitch.tv/?channel=btscsgo',
        raw_url: 'https://www.twitch.tv/btscsgo',
      },
      russian: {
        embed_url: null,
        raw_url: null,
      },
    },
    match_type: 'best_of',
    official_stream_url: 'https://www.twitch.tv/btscsgo',
    forfeit: false,
    opponents: [
      {
        opponent: {
          acronym: null,
          id: 3288,
          image_url:
            'https://cdn.pandascore.co/images/team/image/3288/600px_virtus.pro_2019.png',
          location: 'RU',
          modified_at: '2021-01-29T01:43:55Z',
          name: 'Virtus.pro',
          slug: 'virtus-pro-75b4744b-43d9-4ebd-a8dc-f1e0f9be69b3',
        },
        type: 'Team',
      },
      {
        opponent: {
          acronym: null,
          id: 3217,
          image_url:
            'https://cdn.pandascore.co/images/team/image/3217/220px_fnaticlogo_square.png',
          location: 'GB',
          modified_at: '2021-01-29T01:43:56Z',
          name: 'fnatic',
          slug: 'fnatic-cs-go',
        },
        type: 'Team',
      },
    ],
    id: 581450,
    game_advantage: null,
    games: [
      {
        begin_at: null,
        complete: false,
        detailed_stats: true,
        end_at: null,
        finished: false,
        forfeit: false,
        id: 35136,
        length: null,
        match_id: 581450,
        position: 1,
        status: 'not_started',
        video_url: null,
        winner: {
          id: null,
          type: 'Team',
        },
        winner_type: 'Team',
      },
      {
        begin_at: null,
        complete: false,
        detailed_stats: true,
        end_at: null,
        finished: false,
        forfeit: false,
        id: 35137,
        length: null,
        match_id: 581450,
        position: 2,
        status: 'not_started',
        video_url: null,
        winner: {
          id: null,
          type: 'Team',
        },
        winner_type: 'Team',
      },
      {
        begin_at: null,
        complete: false,
        detailed_stats: true,
        end_at: null,
        finished: false,
        forfeit: false,
        id: 35138,
        length: null,
        match_id: 581450,
        position: 3,
        status: 'not_started',
        video_url: null,
        winner: {
          id: null,
          type: 'Team',
        },
        winner_type: 'Team',
      },
    ],
    winner_id: null,
    number_of_games: 3,
    draw: false,
    detailed_stats: true,
    scheduled_at: '2021-01-31T20:00:00Z',
    begin_at: '2021-01-31T20:00:00Z',
    live: {
      opens_at: '2021-01-31T19:45:00Z',
      supported: true,
      url: 'wss://live.pandascore.co/matches/581450',
    },
  },
  {
    name: 'Grand Final: paiN vs Rebirth',
    rescheduled: false,
    tournament: {
      begin_at: '2021-01-27T21:00:00Z',
      end_at: null,
      id: 5407,
      league_id: 4152,
      live_supported: true,
      modified_at: '2021-01-27T21:36:03Z',
      name: 'Playoffs',
      prizepool: '30000 United States Dollar',
      serie_id: 3299,
      slug: 'cs-go-dreamhack-north-america-open-january-2021-playoffs',
      winner_id: null,
      winner_type: 'Team',
    },
    live_embed_url: 'https://player.twitch.tv/?channel=dreamhackcs',
    end_at: null,
    league_id: 4152,
    serie_id: 3299,
    serie: {
      begin_at: '2021-01-27T21:00:00Z',
      description: null,
      end_at: null,
      full_name: 'North America Open January 2021',
      id: 3299,
      league_id: 4152,
      modified_at: '2021-01-22T09:12:34Z',
      name: 'North America Open January',
      season: null,
      slug: 'cs-go-dreamhack-north-america-open-january-2021',
      tier: 'b',
      winner_id: null,
      winner_type: null,
      year: 2021,
    },
    modified_at: '2021-01-31T03:09:24Z',
    winner: null,
    videogame_version: null,
    original_scheduled_at: '2021-01-31T20:00:00Z',
    slug: 'pain-2021-01-31',
    videogame: {
      id: 3,
      name: 'CS:GO',
      slug: 'cs-go',
    },
    league: {
      id: 4152,
      image_url:
        'https://cdn.pandascore.co/images/league/image/4152/DreamHack_Black-RGB.png',
      modified_at: '2019-10-09T13:32:53Z',
      name: 'DreamHack',
      slug: 'cs-go-dreamhack',
      url: null,
    },
    results: [
      {
        score: 1,
        team_id: 125751,
      },
      {
        score: 0,
        team_id: 126638,
      },
    ],
    status: 'not_started',
    tournament_id: 5407,
    streams: {
      english: {
        embed_url: 'https://player.twitch.tv/?channel=dreamhackcs',
        raw_url: 'https://www.twitch.tv/dreamhackcs',
      },
      official: {
        embed_url: 'https://player.twitch.tv/?channel=dreamhackcs',
        raw_url: 'https://www.twitch.tv/dreamhackcs',
      },
      russian: {
        embed_url: null,
        raw_url: null,
      },
    },
    match_type: 'best_of',
    official_stream_url: 'https://www.twitch.tv/dreamhackcs',
    forfeit: false,
    opponents: [
      {
        opponent: {
          acronym: null,
          id: 125751,
          image_url:
            'https://cdn.pandascore.co/images/team/image/125751/pain-gaming-farnhu45.png',
          location: 'BR',
          modified_at: '2021-01-25T11:14:52Z',
          name: 'paiN',
          slug: 'pain-gaming-cs-go',
        },
        type: 'Team',
      },
      {
        opponent: {
          acronym: null,
          id: 126638,
          image_url:
            'https://cdn.pandascore.co/images/team/image/126638/10357.png',
          location: null,
          modified_at: '2021-01-27T21:36:03Z',
          name: 'Rebirth',
          slug: 'rebirth-esports-cs-go',
        },
        type: 'Team',
      },
    ],
    id: 581331,
    game_advantage: 125751,
    games: [
      {
        begin_at: null,
        complete: false,
        detailed_stats: true,
        end_at: null,
        finished: false,
        forfeit: false,
        id: 35061,
        length: null,
        match_id: 581331,
        position: 1,
        status: 'not_started',
        video_url: null,
        winner: {
          id: null,
          type: 'Team',
        },
        winner_type: 'Team',
      },
      {
        begin_at: null,
        complete: false,
        detailed_stats: true,
        end_at: null,
        finished: false,
        forfeit: false,
        id: 35062,
        length: null,
        match_id: 581331,
        position: 2,
        status: 'not_started',
        video_url: null,
        winner: {
          id: null,
          type: 'Team',
        },
        winner_type: 'Team',
      },
      {
        begin_at: null,
        complete: false,
        detailed_stats: true,
        end_at: null,
        finished: false,
        forfeit: false,
        id: 35063,
        length: null,
        match_id: 581331,
        position: 3,
        status: 'not_started',
        video_url: null,
        winner: {
          id: null,
          type: 'Team',
        },
        winner_type: 'Team',
      },
      {
        begin_at: null,
        complete: false,
        detailed_stats: true,
        end_at: null,
        finished: false,
        forfeit: false,
        id: 35065,
        length: null,
        match_id: 581331,
        position: 4,
        status: 'not_started',
        video_url: null,
        winner: {
          id: null,
          type: 'Team',
        },
        winner_type: 'Team',
      },
    ],
    winner_id: null,
    number_of_games: 5,
    draw: false,
    detailed_stats: true,
    scheduled_at: '2021-01-31T20:00:00Z',
    begin_at: '2021-01-31T20:00:00Z',
    live: {
      opens_at: '2021-01-31T19:45:00Z',
      supported: true,
      url: 'wss://live.pandascore.co/matches/581331',
    },
  },
  {
    name: 'Semifinals: Oceanus vs Bad News Bears',
    rescheduled: false,
    tournament: {
      begin_at: '2021-01-31T21:00:00Z',
      end_at: null,
      id: 5452,
      league_id: 4243,
      live_supported: false,
      modified_at: '2021-01-31T09:52:38Z',
      name: 'Playoffs',
      prizepool: '15000 United States Dollar',
      serie_id: 3321,
      slug: 'cs-go-esea-north-america-cash-cup-4-2021-playoffs',
      winner_id: null,
      winner_type: 'Team',
    },
    live_embed_url: 'https://player.twitch.tv/?channel=hitmediaru5',
    end_at: null,
    league_id: 4243,
    serie_id: 3321,
    serie: {
      begin_at: '2021-01-31T21:00:00Z',
      description: null,
      end_at: null,
      full_name: 'North America Cash Cup Winter 4 2021',
      id: 3321,
      league_id: 4243,
      modified_at: '2021-01-31T08:16:26Z',
      name: 'North America Cash Cup',
      season: 'Winter 4',
      slug: 'cs-go-esea-north-america-cash-cup-4-2021',
      tier: 'd',
      winner_id: null,
      winner_type: null,
      year: 2021,
    },
    modified_at: '2021-01-31T08:24:42Z',
    winner: null,
    videogame_version: null,
    original_scheduled_at: '2021-01-31T21:00:00Z',
    slug: 'oceanus-vs-bad-news-bears-2021-01-31',
    videogame: {
      id: 3,
      name: 'CS:GO',
      slug: 'cs-go',
    },
    league: {
      id: 4243,
      image_url:
        'https://cdn.pandascore.co/images/league/image/4243/798px-ESEA_banner.png',
      modified_at: '2020-11-12T15:51:24Z',
      name: 'ESEA',
      slug: 'cs-go-esea',
      url: 'https://play.esea.net/',
    },
    results: [
      {
        score: 0,
        team_id: 126637,
      },
      {
        score: 0,
        team_id: 125753,
      },
    ],
    status: 'not_started',
    tournament_id: 5452,
    streams: {
      english: {
        embed_url: null,
        raw_url: null,
      },
      official: {
        embed_url: 'https://player.twitch.tv/?channel=hitmediaru5',
        raw_url: 'https://www.twitch.tv/hitmediaru5',
      },
      russian: {
        embed_url: 'https://player.twitch.tv/?channel=hitmediaru5',
        raw_url: 'https://www.twitch.tv/hitmediaru5',
      },
    },
    match_type: 'best_of',
    official_stream_url: 'https://www.twitch.tv/hitmediaru5',
    forfeit: false,
    opponents: [
      {
        opponent: {
          acronym: null,
          id: 126637,
          image_url:
            'https://cdn.pandascore.co/images/team/image/126637/10282.png',
          location: null,
          modified_at: '2021-01-31T08:19:00Z',
          name: 'Oceanus',
          slug: 'oceanus-gaming',
        },
        type: 'Team',
      },
      {
        opponent: {
          acronym: null,
          id: 125753,
          image_url:
            'https://cdn.pandascore.co/images/team/image/125753/bad_news_bears_logo.png',
          location: 'US',
          modified_at: '2021-01-31T08:19:01Z',
          name: 'Bad News Bears',
          slug: 'bad-news-bears',
        },
        type: 'Team',
      },
    ],
    id: 582066,
    game_advantage: null,
    games: [
      {
        begin_at: null,
        complete: false,
        detailed_stats: true,
        end_at: null,
        finished: false,
        forfeit: false,
        id: 35775,
        length: null,
        match_id: 582066,
        position: 1,
        status: 'not_started',
        video_url: null,
        winner: {
          id: null,
          type: 'Team',
        },
        winner_type: 'Team',
      },
      {
        begin_at: null,
        complete: false,
        detailed_stats: true,
        end_at: null,
        finished: false,
        forfeit: false,
        id: 35776,
        length: null,
        match_id: 582066,
        position: 2,
        status: 'not_started',
        video_url: null,
        winner: {
          id: null,
          type: 'Team',
        },
        winner_type: 'Team',
      },
      {
        begin_at: null,
        complete: false,
        detailed_stats: true,
        end_at: null,
        finished: false,
        forfeit: false,
        id: 35777,
        length: null,
        match_id: 582066,
        position: 3,
        status: 'not_started',
        video_url: null,
        winner: {
          id: null,
          type: 'Team',
        },
        winner_type: 'Team',
      },
    ],
    winner_id: null,
    number_of_games: 3,
    draw: false,
    detailed_stats: true,
    scheduled_at: '2021-01-31T21:00:00Z',
    begin_at: '2021-01-31T21:00:00Z',
    live: {
      opens_at: null,
      supported: false,
      url: null,
    },
  },
];

export default response;
